export const ROTOR_URL = 'http://rutor.info'
export const BASE_SEARCH_URL = ROTOR_URL + '/search/0/0/000/9'
export const MAGNET_KEY = 'magnet:?xt'
export const SPLIT_MAGNET_STRING = 'urn:btih:'
export const BASE_IMDB_SEARCH_URL = 'https://api.themoviedb.org/3'